### ISSUE TITLE
importSchema does not work with .gql extension

### ISSUE THREAD

**Issue by jloveric** [ardatan/graphql-import#244]
I have the exact same schema, one with the .graphql extension and the other with .gql extension.  importSchema works on the first (.graphql), but not the second 

    const { importSchema } = require('graphql-import')
    //let typeDefs = importSchema(__dirname+"/schema.graphql")
    let typeDefs = importSchema(__dirname+"/schema.gql") 
    console.log(typeDefs)

In the second case, the error thrown is

    /<DIRECTORY>/node_modules/graphql/language/lexer.js:316
      throw (0, _error.syntaxError)(source, position, unexpectedCharacterMessage(code));
      ^
    Syntax Error: Cannot parse the unexpected character "/".

This is with graphql-import 0.7.1

Thanks!

**Comment by TobiasBales** [comment]
I just noticed the same behaviour. I worked around it by reading the file and passing that into import schema which seems to work

```ts
const schema = importSchema(
  fs.readFileSync(resolve(__dirname, 'graphql', 'schema.gql')).toString()
);
```

Proper support for `.gql` would be nice though since some extensions (vs code) expect that file extension

**Comment by wingertge** [comment]
The same issue is present with *.graphqls files. Reading the string manually doesn't work since it messes up the import paths (all imports are resolved from project root - if I use importSchema normally with a file name it resolves from the main file).

**Comment by jsonmaur** [comment]
Any update on this? Still an issue when using `.gql` schema files.

**Comment by SachaG** [comment]
This doesn't seem to be fixed for me yet?

**Comment by ardatan** [comment]
@SachaG It's not been released yet

**Comment by ardatan** [comment]
Hi @jloveric , @TobiasBales , @wingertge , @jsonmaur and @SachaG  !
In 1.0.0 beta release, we introduced a lot of changes including different methods to load your schema such as URL Endpoint, graphql/gql files, TS/JS code files, Prisma endpoint, Apollo Engine and JSON files.

Could you install `graphql-import@beta` to try new changes? Don't forget to modify your code regarding to the migration notes in `README`. 
https://github.com/ardatan/graphql-import#updating-from-07x

So you can try loading your `.gql` files like below;
```ts
import { join } from 'path';
import { importSchema } from 'graphql-import';

let typeDefs = await importSchema(join(__dirname, '/schema.gql')); 
console.log(typeDefs)
```

**Comment by ardatan** [comment]
Available in 1.0.0!
